### ISSUE TITLE
Wyze Bulb Support

### ISSUE THREAD

**Issue by seantdavidson** [elahd/wyze_plug_flasher#2]
I tried flashing a wyze bulb I had laying around that was not using. While it worked sort of it kept flashing so I think there is something that can be fixed. I know that tasmota has been installed on these but you have to take them apart. Sorry I am not smart enough to understand the OTA flashing I would pop open and flash by soldering but bulbs are a different beast. Not sure if you could see if you can update this for the bulb.
The tasmota template is here.

https://templates.blakadder.com/wyze_WLPA19.html

**Comment by elahd** [comment]
Solved [via reddit](https://www.reddit.com/r/wyzecam/comments/l54d8b/instructions_and_software_install_tasmota_on_wyze/).
