### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by HclX** [elahd/wyze_plug_flasher#3]
Can you post which exact version of the SDK you use? I'm trying to build it with this SDK release: https://github.com/espressif/ESP8266_RTOS_SDK/releases/tag/v3.3
ran into the following errors

```
In file included from /project/wyze_plug_flasher/components/app_update/esp_ota_ops.c:32:0:
/project/wyze_plug_flasher/components/app_update/include/esp_ota_ops.h:24:28: fatal error: esp_app_format.h: No such file or directory
compilation terminated.
/project/ESP8266_RTOS_SDK/make/component_wrapper.mk:291: recipe for target 'esp_ota_ops.o' failed
make[1]: *** [esp_ota_ops.o] Error 1
/project/ESP8266_RTOS_SDK/make/project.mk:571: recipe for target 'component-app_update-build' failed
make: *** [component-app_update-build] Error 2
```

**Comment by elahd** [comment]
I cloned the repo directly using git, then ran the SDK's install/export scripts. I cloned the master branch, but it's probably a better idea to use the release branch. I can confirm that both branches build successfully. I also get build errors when using the official SDK release .zip.

`git clone https://github.com/espressif/ESP8266_RTOS_SDK.git
git switch release/v3.4`

My directory structure is:

1. **ESP8266_RTOS_SDK:** ~/esp/ESP8266_RTOS_SDK
2. **Xtensa Toolchain:** ~/esp/xtensa-lx106-elf
3. **Wyze Plug Flasher:** ~/esp/wyze_flash/wyze_plug_flasher

The double nesting on the WPF directory is a remnant from an earlier version of the project. If you change that, be sure to update line 5 of CMakeLists.txt in this repo's root -- it uses a relative path.

**Comment by HclX** [comment]
Yep, verified master branch and release 3.4-rc works.  

Also, I enabled the backup and erasing rf_calibration data code and don't see anything goes strangely:
1. the backup hash doesn't match because the flash size difference. For my case, the flash dump from plug indicates it has 2MB flash, however, the nodemcu I'm flashing to has 4MB bytes. When you dump the flash, you will get 4MB backup, whose hash will not match the original flash, but i don't think this is a big deal.
2.   the rf_calibration code doesn't cause any noticeable problem.

I do see one problem when you trying to format the flash byte to size string:
```
  const char *FlashSize = "";
  switch (flash_data_addr[3] & 0xF0) {
  case 0x0:
    FlashSize = "512K";
    break;
  case 0x1:
    FlashSize = "256K";
    break;
```
the result will be X0 instead of X, so in this case, you should be comparing it with 0x00, 0x10, 0x20, etc. But this shouldn't affect any functionality.

**Comment by elahd** [comment]
Thanks for looking through this!

I turned the backup function back on and fixed the hex formatting bug.

I also enabled the rf calibration delete code. I remember running into issues with that block of code, but it seems to have sorted itself out now. With that said, I don't have any donor plugs on hand to test the code, so I can't be sure that this code is enough to completely eliminate the need to run `Reset 5`. The issue was never reproducible on the esp8266 dev boards.

**Comment by xthedakmanx** [comment]
> Thanks for looking through this!
> 
> I turned the backup function back on and fixed the hex formatting bug.
> 
> I also enabled the rf calibration delete code. I remember running into issues with that block of code, but it seems to have sorted itself out now. With that said, I don't have any donor plugs on hand to test the code, so I can't be sure that this code is enough to completely eliminate the need to run `Reset 5`. The issue was never reproducible on the esp8266 dev boards.

I can confirm that a Reset 5 is still needed, at least in my case.
Flashed 4 plugs, didn't do a reset 5 on one and the only reason I noticed is because it kept going offline
