### ISSUE TITLE
Bulb still on when turned off

### ISSUE THREAD

**Issue by imhotep** [elahd/wyze_plug_flasher#4]
There seems to be an LED that says on even when the bulb is turned off with the given template

```
{"NAME":"Wyze Bulb","GPIO":[5728,0,0,0,0,0,0,0,0,416,417,0,0,0],"FLAG":0,"BASE":48}
```

![PXL_20210209_033729413](https://user-images.githubusercontent.com/93032/107406051-d3847000-6abc-11eb-9811-4965880014d5.jpg)

Any idea why? Is there another GPIO for it? Currently I only have GPIO 13 -> PWM 1 and GPIO 14 -> PWM2

**Comment by digiblur** [comment]
Check this thread as I do remember a new feature for it. https://github.com/arendst/Tasmota/pull/10196

**Comment by imhotep** [comment]
Thanks @digiblur. Works with current development branch of [Tasmota (9.2.0.6)](http://ota.tasmota.com/tasmota/). Closing this
