### ISSUE TITLE
Does not seem to work with the newer model WLPP1CFH-1

### ISSUE THREAD

**Issue by Ken271** [elahd/wyze_plug_flasher#5]
I had no problem with an older one that did not have bluetooth like the newer ones do. That one worked perfectly other than I need to type python in place of py. The newer ones do allow me to view the info using "python wyze_updater.py" list
result
INFO:root:Trying saved credentials from .tokens.
Device Type:       Plug (WLPP1CFH)
Device MAC:        2CAA8EF1D7A5
Firmware Version:  1.2.0.76
Device Name:       ender 5 plus

 but the firmware updater command "python wyze_updater.py update -s -d 2CAA8EF1D7A5 -f wyze_plug_flasher.bin"  just moves along and does not do anything after the username and password are put in. . The original Wyze firmware is still on it.
This was tried as both  ../wyze_plug_flasher.bin wyze_plug_flasher.bin

C:\wpf\WyzeUpdater>python wyze_updater.py update -s -d 2CAA8EF1D7A4 -f wyze_plug_flasher.bin
INFO:root:Trying saved credentials from .tokens.
INFO:root:Checking device, mac=2CAA8EF1D7A5

Device type:      Plug (WLPP1CFH)
Device name:      ender 5 plus
Firmware version: 1.2.0.76
IP Address:       10.0.0.164

Pushing firmware to this device? [y/N]:y
INFO:root:Serving firmware file 'wyze_plug_flasher.bin' as 'https://10.0.0.29/firmware.bin', md5=c1cd336c04a3c74e315edac00afd117c
Press Ctrl+C when all the updates are done...
.....10.0.0.164 - - [11/Feb/2021 19:26:32] "GET /firmware.bin HTTP/1.1" 200 -

I guess the next step is prying it apart and seeing what is inside.

**Comment by Ken271** [comment]
Well it was easy to solve. The Bluetooth should have been a hint to me. It has an ESP32 inside.
I see pads to solder to , now to see what needs to be done to do this .

**Comment by elahd** [comment]
Yep, this won't work on an ESP32. Different SDK.

If you plan to flash via wire, would you be able to take and share a firmware dump?

**Comment by Ken271** [comment]
Sure, can I send the file to you on this ? Not sure if Gitbub allows attachments, I know thingiverse does not. I'm Skrutch on Thingivers and sent you a message from there earlier todfay.
    On Friday, February 12, 2021, 10:53:29 AM EST, Elahd Bar-Shai <notifications@github.com> wrote:  
 
 


Yep, this won't work on an ESP32. Different SDK.

If you plan to flash via wire, would you be able to take and share a firmware dump?

**Comment by Ken271** [comment]
Here is the zip with the full 4mb file enclosed. Did you need other parts or a smaller slice of the firmware ?Not sure if it will get to you if not we can try another way.

    On Friday, February 12, 2021, 7:17:00 PM EST, Ken <wetzk@yahoo.com> wrote:  
 
  
Sure, can I send the file to you on this ? Not sure if Gitbub allows attachments, I know thingiverse does not. I'm Skrutch on Thingivers and sent you a message from there earlier todfay.
    On Friday, February 12, 2021, 10:53:29 AM EST, Elahd Bar-Shai <notifications@github.com> wrote:  
 
 


Yep, this won't work on an ESP32. Different SDK.

If you plan to flash via wire, would you be able to take and share a firmware dump?

**Comment by Ken271** [comment]
I created one for you. The info is on thingiverse since this seems to be open to anyone to read.

**Comment by wstrater** [comment]
> Well it was easy to solve. The Bluetooth should have been a hint to me. It has an ESP32 inside.
> I see pads to solder to , now to see what needs to be done to do this .

I managed to brick one of these plugs and was trying to open it up. Never opened a glued plugged and was not having much success. How did you open up yours?

Wes.

**Comment by Ken271** [comment]
I ran a heat gun along one of the long sides. When it was warm and slightly pliable a spatula was worked in and the side bowled out a bit. After it cooled the tools used to open cell phones were able to finish breaking the glue free. Later the housing was heated up and pressed against a flat surface to reform it.
    On Sunday, February 21, 2021, 4:43:58 PM EST, wstrater <notifications@github.com> wrote:  
 
 



Well it was easy to solve. The Bluetooth should have been a hint to me. It has an ESP32 inside.
I see pads to solder to , now to see what needs to be done to do this .


I managed to brick one of these plugs and was trying to open it up. Never opened a glued plugged and was not having much success. How did you open up yours?

Wes.

**Comment by mkormendy** [comment]
Is it possible to make a different firmware with SDK for the ESP32?

**Comment by elahd** [comment]
@mkormendy: It’s in the roadmap. I want to stabilize the experience for the ESP8266 first. I’ll get started on an ESP32 version later this summer.

The ESP32 will require a different approach than the ESP8266. I haven’t dug too deep into the architecture, but it looks like I’ll need to make a custom intermediate bootloader in addition to an ESP32 variant of the esp2ino program itself.

**Comment by mkormendy** [comment]
Beware that some ESP32 chips have their firmware locked. Most often they aren't but, another developer I know told me that can also be a problem when flashing OTA.
